version: "2.1"
services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
    ports:
      - 15672:15672
      - 5672:5672
    healthcheck:
        test: rabbitmq-diagnostics -q ping
        interval: 5s
        timeout: 10s
        retries: 5

  server:
    build:
      context: .
      dockerfile: RPCRabbitMQ.Server/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy

  client:
    build:
      context: .
      dockerfile: RPCRabbitMQ.Client/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
